version: '3.8'

services:
  honeypot:
    build:
      context: .
    ports:
      - "8080:8080"  # HTTP
      - "2222:2222"  # SSH
      - "2121:2121"  # FTP
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb-honeypot
    ports:
      - "27069:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
    driver: local
